framework:
    messenger:
        default_bus: messenger.bus.default
        # Remove or comment out any async routing for emails
        # routing:
        #     'App\Message\YourEmailMessage': async
