security:
    password_hashers:
        App\Entity\Admin:
            algorithm: auto

    providers:
        # Load users from the Admin entity
        app_user_provider:
            entity:
                class: App\Entity\Admin
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\AdminAuthenticator
            logout:
                path: app_logout
                target: /
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /

    access_control:
        # Protect the dashboard
        - { path: ^/dashboard, roles: ROLE_ADMIN }
        # Optionally, protect other admin routes
        - { path: ^/cart, roles: ROLE_ADMIN }
        - { path: ^/product, roles: ROLE_ADMIN }
        - { path: ^/category, roles: ROLE_ADMIN }
        - { path: ^/order, roles: ROLE_ADMIN }
