# config/packages/security.yaml
security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: auto
        App\Entity\Admin:
            algorithm: auto

    providers:
        admin_provider:
            entity:
                class: App\Entity\Admin
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            pattern: ^/admin
            provider: admin_provider
            lazy: false
            form_login:
                login_path: admin_login        # GET /admin/login
                check_path: admin_login        # POST /admin/login
                default_target_path: /admin/dashboard
                always_use_default_target_path: true
            logout:
                path: admin_logout
                target: admin_login

    access_control:
        - { path: ^/admin/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY } # important: exact match
        - { path: ^/admin, roles: ROLE_ADMIN }
