# config/routes.yaml
app_login:
    path: /
    controller: App\Controller\AdminSecurityController::login

app_logout:
    path: /logout
    controller: App\Controller\AdminSecurityController::logout

controllers:
    resource: ../src/Controller/
    type: attribute
