App\Entity\OrderItem:
  type: entity
  table: order_items
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    quantite: { type: integer }
    prixUnitaire: { type: decimal, precision: 10, scale: 2 }
  manyToOne:
    order:
      targetEntity: App\Entity\Order
      inversedBy: orderItems
      joinColumn: { nullable: false }
    product:
      targetEntity: App\Entity\Product
      joinColumn: { nullable: false }
