App\Entity\User:
  type: entity
  table: users
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    nom: { type: string, length: 100 }
    prenom: { type: string, length: 100 }
    email: { type: string, length: 180, unique: true }
    password: { type: string }
    actif: { type: boolean }
    dateCreation: { type: datetime_immutable }
  oneToMany:
    orders:
      targetEntity: App\Entity\Order
      mappedBy: user
    addresses:
      targetEntity: App\Entity\Address
      mappedBy: user
    carts:
      targetEntity: App\Entity\Cart
      mappedBy: user
